### ISSUE TITLE
The colloquial term is 'debone' rather than 'unbone'

### ISSUE THREAD

**Issue by liyang** [fumieval/monad-skeleton#1]
'Unbone' does exist in the dictionary (much to my surprise), but 'debone' is the word everyone uses nowadays.

**Comment by fumieval** [comment]
I've searched of that from Wiktionary (https://en.wiktionary.org/wiki/unbone) and I've gone ahead.

But maybe I should use the word 'debone'.

**Comment by liyang** [comment]
The [etymology of ‘bone’](https://en.wiktionary.org/wiki/bone#Etymology_1) suggests it's of Germanic origin (amongst others) so the ‘un-’ prefix would make more sense, but I have never heard anyone talk of ‘unboning’ a chicken, for example; if you Google ‘unbone’, none of the results on the first page contains an actual usage of the process of removing bones from meat.

I would guess the 'unbone' entry you see in Wiktionary comes from a very archaic dictionary. :)

**Comment by fumieval** [comment]
Released 0.1.2.1. Thanks!
